name: github-com-kemadev-repository-template-config-github-repo
description: ""
runtime: go
config:
  pulumi:disable-default-providers:
    description: Disable default providers to enforce using configured ones
    value:
      - '*'
