version: 3

vars:
  tmpDir: /tmp
  taskSuccessMarker: task-success

  gitCli: git
  reusableConfigsRepoPrefix: https://github.com
  reusableConfigsRepoOrgAndName: kemadev/workflows-and-actions
  reusableConfigsSubdir: config/reusable

  dockerRunBase: docker run --rm -it

  dockerLinter: '{{ .dockerRunBase }} ghcr.io/hadolint/hadolint'
  ghaLinter: '{{ .dockerRunBase }} -v "$(pwd):/repo" --workdir /repo rhysd/actionlint:latest -color'
  secretsLinter: '{{ .dockerRunBase }} -v "$(pwd):/pwd" trufflesecurity/trufflehog:latest git "file:///pwd" --since-commit HEAD'
  sastLinter: '{{ .dockerRunBase }} -v "$(pwd):/src" semgrep/semgrep:latest semgrep scan --config auto'
  goLinter: '{{ .dockerRunBase }} -v $(pwd):/app -v ~/.cache/golangci-lint:/root/.cache --workdir /app golangci/golangci-lint:latest golangci-lint run --config /app/{{ .reusableConfigsSubdir }}/.golangci.yaml'
  yamlLinter: yamllint
  markdownLinter: '{{ .dockerRunBase }} -v "$(pwd):/workdir" davidanson/markdownlint-cli2:latest --config {{ .reusableConfigsSubdir }}/.markdownlint.yaml "**/*.md"'
  shellLinter: '{{ .dockerRunBase }} -v "$(pwd):/mnt" koalaman/shellcheck:latest $(find . -name "*.sh" | tr "\n" " ")'

run: once

# TODO checkout reusable configs at first for all tasks

tasks:
  # Checkout reusable configs
  checkout-reusable:
    desc: Checkout reusable configs, only subdirectory
    internal: true
    status:
      - '[ -f {{ .reusableConfigsSubdir }}/{{ .taskSuccessMarker }} ]'
    cmds:
      - '{{ .gitCli }} clone --depth 1 {{ .reusableConfigsRepoPrefix }}/{{ .reusableConfigsRepoOrgAndName }} {{ .tmpDir }}/{{ .reusableConfigsRepoOrgAndName }}'
      - find {{ .tmpDir }}/{{ .reusableConfigsRepoOrgAndName }}/{{ .reusableConfigsSubdir }} -maxdepth 1 -mindepth 1 -name '*' ! -name '*.md' ! -name '.gitignore' -exec cp {} {{ .reusableConfigsSubdir }} \;
      - touch {{ .reusableConfigsSubdir }}/{{ .taskSuccessMarker }}

  reset-reusable:
    desc: Reset reusable configs
    cmds:
      - rm -rf {{ .reusableConfigsSubdir }}/{{ .taskSuccessMarker }}
      - rm -rf {{ .tmpDir }}/{{ .reusableConfigsRepoOrgAndName }}

  # Docker
  docker-lint:
    desc: Lint Dockerfiles
    deps:
      - checkout-reusable
    cmds:
      - find . -name '*Dockerfile*' -print0 | xargs -0 -I {} sh -c 'cat {} | {{ .dockerLinter }}'

  # GitHub Actions
  gha-lint:
    desc: Lint GitHub Actions workflows
    deps:
      - checkout-reusable
    cmds:
      - '{{ .ghaLinter }}'

  # Secrets
  secrets-lint:
    desc: Lint secrets
    deps:
      - checkout-reusable
    cmds:
      # TODO git add before running otherwise no scan
      - '{{ .secretsLinter }}'

  # Static Application Security Testing (SAST)
  sast-lint:
    desc: Lint source code
    deps:
      - checkout-reusable
    cmds:
      - '{{ .sastLinter }}'

  # Go
  go-lint:
    desc: Lint Go source code
    deps:
      - checkout-reusable
    cmds:
      - '{{ .goLinter }}'

  # Markdown
  markdown-lint:
    desc: Lint Markdown files
    deps:
      - checkout-reusable
    cmds:
      - '{{ .markdownLinter }}'

  # Shell
  shell-lint:
    desc: Lint shell scripts
    deps:
      - checkout-reusable
    cmds:
      - '{{ .shellLinter }}'

  # YAML
  yaml-lint:
    desc: Lint YAML files
    deps:
      - checkout-reusable
    cmds:
      - find . -name '*.yaml' -print0 | xargs -0 -I {} sh -c '{{ .yamlLinter }} {}'
