# Project root directory (in container)
root = "."
# Testdata directory
testdata_dir = "testdata"
# Tmp directory
tmp_dir = "/tmp"

[build]
# Build command, `bootstrap` as only binary is required for AWS Lambda provided runtime
cmd = "CGO_ENABLED=0 go build -tags lambda.norpc -o /var/runtime/bootstrap ./cmd/${GO_MAIN_FILE_DIR}"
# Bin to run and reload
bin = "/lambda-entrypoint.sh"
# Bin args
args_bin = ["whatever"]
# Directories to exclude
exclude_dir = [
  "testdata",
  "build",
  "dist",
  "vendor",
  "deploy",
  "example",
  "schema",
  "tool",
]
# File extensions to include
include_ext = ["go", "tpl", "tmpl", "html"]
# Regex to exclude
exclude_regex = ["_test.go"]
# Log file (located in tmp_dir)
log = "air.log"
# Send interrupt before kill
send_interrupt = true
# Stop running old binary when build error
stop_on_error = false
# Restart on exit
rerun = false

[color]
# App log color
main = "magenta"
# Watcher log color
watcher = "cyan"
# Builder log color
build = "yellow"
# Runner log color
runner = "green"

[log]
# Show only main log (not watcher, builder, runner)
main_only = true
# Log timestamps
time = false

[misc]
# Delete tmp directory on exit
clean_on_exit = false

[screen]
# Clear screen on reload
clear_on_rebuild = true
# Keep scroll on reload
keep_scroll = true
