version: "3"

vars:
  baseDir: "../.."
  configDir: "config"
  toolsDir: "tool"
  distDir: "dist"

run: once

includes:
  custom:
    taskfile: "custom"
    dir: "{{ .baseDir }}"
    optional: true
  dev:
    taskfile: "dev"
    dir: "{{ .baseDir }}"
  go:
    taskfile: "go"
    dir: "{{ .baseDir }}"
  run:
    taskfile: "run"
    dir: "{{ .baseDir }}"
