name: bar

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, world!' && exit 2
