name: Docker - CI
description: Lint Dockerfiles

on:
  pull_request:
    paths:
      - '**/*Dockerfile'
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  docker-ci:
    name: Docker - CI
    uses: kemadev/workflows-and-actions/.github/workflows/docker-ci.yaml@main
    permissions:
      contents: read
      checks: write
