name: Global - CI

on:
  pull_request: {}
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  global-ci:
    name: Global - CI
    runs-on: ubuntu-latest
    steps:
      - name: Foo
        run: cat **/*.sh
