name: Global - CI
description: Perform Static Application Security Testing and secrets scanning

on:
  pull_request: {}
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  global-ci:
    name: Global - CI
    uses: kemadev/workflows-and-actions/.github/workflows/global-ci.yaml@main
    permissions:
      contents: read
      issues: write
      pull-requests: write
