name: Go - CD IssueOps

on:
  issue_comment:
    types:
      - created

defaults:
  run:
    shell: bash

jobs:
  go-cd-issueopos:
    name: Go - CD IssueOps
    uses: kemadev/workflows-and-actions/.github/actions/issue-command-dispatch.yaml@main
    # uses: kemadev/workflows-and-actions/.github/workflows/go-cd-issueops.yaml@main
    permissions:
      pull-requests: write
      deployments: write
      contents: write
      checks: read
      statuses: read
      packages: write
