name: Go - CI

on:
  pull_request:
    paths:
      - go.mod
      - go.sum
      - '**/*.go'
  workflow_dispatch: {}

jobs:
  go-ci:
    name: Go - CI
    uses: kemadev/workflows-and-actions/.github/workflows/go-ci.yaml@main
    permissions:
      contents: read
      pull-requests: write
      checks: write
