name: Go - CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy
        type: string
        default: main
      ref:
        description: Git ref to deploy, defaults to *workflow branch* (selector above) HEAD
        required: false
        type: string
      enable_rollback:
        description: Enable rollback in case of deployment failure
        type: boolean
        default: true
      rollback:
        description: Wether to rollback instead of deploying
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  go-cd:
    name: Go - CD
    permissions:
      pull-requests: write
      deployments: write
      contents: write
      packages: write
    uses: kemadev/workflows-and-actions/.github/workflows/go-cd.yaml@main
    with:
      sha: ${{ github.event.inputs.ref != '' && github.event.inputs.ref || github.sha }}
      ref: ${{ github.event.inputs.ref != '' && github.event.inputs.ref || github.sha }}
      base_ref: ${{ github.event.inputs.environment }}
      # fromJson is used to convert the string to a boolean
      enable_rollback: ${{ fromJson(github.event.inputs.enable_rollback) }}
      # fromJson is used to convert the string to a boolean
      rollback: ${{ fromJson(github.event.inputs.rollback) }}
