name: Go - CD

on:
  workflow_dispatch:
    inputs:
      sha:
        description: SHA to deploy
        type: string
        default: latest
      environment:
        description: Environment to deploy
        type: string
        default: main
      enable_rollback:
        description: Enable rollback in case of deployment failure
        type: boolean
        default: true
      rollback:
        description: Wether to rollback instead of deploying
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  go-cd:
    name: Go - CD
    permissions:
      pull-requests: write
      deployments: write
      contents: write
      packages: write
    uses: kemadev/workflows-and-actions/.github/workflows/go-cd.yaml@main
    with:
      sha: ${{ github.event.inputs.sha }}
      ref: ${{ github.event.inputs.sha }}
      base_ref: ${{ github.event.inputs.environment }}
      # enable_rollback: ${{ github.event.inputs.enable_rollback }}
      rollback: ${{ github.event.inputs.rollback }}
