name: Housekeep - Report stale branches

on:
  schedule:
    # Each day at 3:00 AM
    - cron: "0 3 * * *"
  workflow_dispatch: {}

jobs:
  report-stale-branches:
    name: Report stale branches
    permissions:
      contents: read
      issues: write
    uses: kemadev/workflows-and-actions/.github/workflows/housekeep-stale-branches.yaml@main
