name: Housekeep - Tidy stale Issues & PRs

on:
  schedule:
    # Each day at 3:00 AM
    - cron: "0 3 * * *"
  workflow_dispatch: {}

jobs:
  stale:
    name: Tidy stale Issues & PRs
    permissions:
      issues: write
      pull-requests: write
    uses: kemadev/workflows-and-actions/.github/workflows/housekeep-stale-issue-pr.yaml@main
