name: Markdown - CI
description: Lint markdown files

on:
  pull_request:
    paths:
      - '**/*.md'
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  markdown-ci:
    name: Markdown - CI
    uses: kemadev/workflows-and-actions/.github/workflows/markdown-ci.yaml@main
    permissions:
      contents: read
      checks: write
