name: PR - Check title
description: Check PR title is a conventional commit message

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - unlocked

jobs:
  check-pr-title:
    name: Check PR title
    permissions:
      contents: none
    uses: kemadev/workflows-and-actions/.github/workflows/pr-check-title.yaml@main
