name: Housekeep - Report failed workflows

on:
  workflow_run:
    workflows:
      - '*'
    types:
      - completed
    branches:
      - main
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

# Avoid parallel edit of the Issue
concurrency: housekeep-report-failed-workflows

env:
  HOUSEKEEP_FAILED_WORKFLOWS_SCRIPT_DIR: .github/workflows/script/reusable/housekeep-failed-workflows

jobs:
  report-failed-workflows:
    name: Report failed workflows
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Checkout reusable workflow scripts and configs
        id: checkout-reusable-scripts-and-configs
        uses: kemadev/workflows-and-actions/.github/actions/checkout-reusable-scripts-and-configs@main
      - name: Report failed workflows
        id: report-failed-workflows
        working-directory: ${{ env.HOUSEKEEP_FAILED_WORKFLOWS_SCRIPT_DIR }}
        env:
          GH_TOKEN: ${{ github.token }}
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
          WORKFLOW_NAME: ${{ github.event.workflow_run.name }}
          WORKFLOW_RUN_TITLE: ${{ github.event.workflow_run.display_title }}
          CONCLUSION: ${{ github.event.workflow_run.conclusion }}
          HTML_URL: ${{ github.event.workflow_run.html_url }}
          CREATED_AT: ${{ github.event.workflow_run.created_at }}
          UPDATED_AT: ${{ github.event.workflow_run.updated_at }}
          ACTOR_TYPE: ${{ github.event.workflow_run.actor.type }}
          ACTOR_HTML_URL: ${{ github.event.workflow_run.actor.html_url }}
          TRIGGERING_ACTOR_TYPE: ${{ github.event.workflow_run.triggering_actor.type }}
          TRIGGERING_ACTOR_HTML_URL: ${{ github.event.workflow_run.triggering_actor.html_url }}
        run: |
          go run ./...
