name: Housekeep - Report failed workflows

on:
  workflow_run:
    workflows:
      - '*'
    types:
      - completed
    branches:
      - main
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  report-failed-workflows:
    name: Report failed workflows
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Checkout reusable workflow scripts and configs
        id: checkout-reusable-scripts-and-configs
        uses: kemadev/workflows-and-actions/.github/actions/checkout-reusable-scripts-and-configs@main
      - name: Report failed workflows
        id: report-failed-workflows
        env:
          GH_TOKEN: ${{ github.token }}
          WORKFLOW_URL: ${{ github.event.workflow_run.workflow_url }}
          WORKFLOW_ID: ${{ github.event.workflow_run.workflow_id }}
          NAME: ${{ github.event.workflow_run.name }}
          CONCLUSION: ${{ github.event.workflow_run.conclusion }}
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
          # ACTOR: ${{ fromJson(github.event.workflow_run.actor) }}
          CREATED_AT: ${{ github.event.workflow_run.created_at }}
          HTML_URL: ${{ github.event.workflow_run.html_url }}
          JOBS_URL: ${{ github.event.workflow_run.jobs_url }}
          LOGS_URL: ${{ github.event.workflow_run.logs_url }}
          NODE_ID: ${{ github.event.workflow_run.node_id }}
          # PULL_REQUESTS: ${{ fromJson(github.event.workflow_run.pull_requests) }}
          RUN_NUMBER: ${{ github.event.workflow_run.run_number }}
          # TRIGGERING_ACTIOR: ${{ fromJson(github.event.workflow_run.triggering_actor) }}
          UPDATED_AT: ${{ github.event.workflow_run.updated_at }}
        run: ./.github/script/reusable/report-failed-workflows/report-failed-workflows.sh
