name: Housekeep - Report failed workflows

on:
  workflow_run:
    workflows:
      - '*'
    types:
      - completed
    branches:
      - main
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  report-failed-workflows:
    name: Report failed workflows
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Checkout reusable workflow scripts and configs
        id: checkout-reusable-scripts-and-configs
        uses: kemadev/workflows-and-actions/.github/actions/checkout-reusable-scripts-and-configs@main
      - name: Report failed workflows
        id: report-failed-workflows
        env:
          GH_TOKEN: ${{ github.token }}
          NAME: ${{ github.event.workflow_run.name }}
          CONCLUSION: ${{ github.event.workflow_run.conclusion }}
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
          CREATED_AT: ${{ github.event.workflow_run.created_at }}
          HTML_URL: ${{ github.event.workflow_run.html_url }}
          UPDATED_AT: ${{ github.event.workflow_run.updated_at }}
          ACTOR_LOGIN: ${{ github.event.workflow_run.actor.login }}
          ACTOR_NAME: ${{ github.event.workflow_run.actor.name }}
          ACTOR_TYPE: ${{ github.event.workflow_run.actor.type }}
          ACTOR_HTML_URL: ${{ github.event.workflow_run.actor.html_url }}
          TRIGGERING_ACTOR_LOGIN: ${{ github.event.workflow_run.triggering_actor.login }}
          TRIGGERING_ACTOR_NAME: ${{ github.event.workflow_run.triggering_actor.name }}
          # PULL_REQUESTS: ${{ fromJson(github.event.workflow_run.pull_requests) }}
          TRIGGERING_ACTOR_TYPE: ${{ github.event.workflow_run.triggering_actor.type }}
          TRIGGERING_ACTOR_HTML_URL: ${{ github.event.workflow_run.triggering_actor.html_url }}
          DISPLAY_TITLE: ${{ github.event.workflow_run.display_title }}
        run: ./.github/script/reusable/report-failed-workflows/report-failed-workflows.sh
