name: Website - CI

on:
  pull_request:
    paths:
      - "deploy/**.go"
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  report-security:
    name: Report security
    permissions:
      contents: read
      pull-requests: write
    uses: kemadev/workflows-and-actions/.github/workflows/website-ci.yaml@main
