name: Wiki - Sync

on:
  push:
    branches:
      - main
    paths:
      - 'doc/**.md'

defaults:
  run:
    shell: bash

jobs:
  wiki-sync:
    name: Wiki - Sync
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Sync wiki
        id: sync-wiki
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "kemadev+github-actions[bot]@users.noreply.github.com"
          git clone https://github.com/${{ github.repository }}.wiki ${{ runner.temp }}/repo
          cd ${{ runner.temp }}/repo
          rm -rf *
          cp -r ${{ github.workspace }}/* .
          git add .
          git commit -m "Sync wiki - ${{ github.sha }}"
          git push
